### ISSUE TITLE
Don't display grasps

### ISSUE THREAD

**Issue by ZQ32** [atenpas/agile_grasp#12]
Follow the tutorial to operate a pcd file that has the following display but does not display any images and crawls.

![Screenshot from 2019-08-23 10-06-15](https://user-images.githubusercontent.com/46440854/63659943-c3080900-c7e6-11e9-9f43-c27fad142988.png)

**Comment by atenpas** [comment]
`Usage: test_svm pcd_filepath svm_filepath [num_samples] [num_threads] [min_handle_inliers] [plot_mode]`

Set `plot_mode` to `2` to visualize the grasps. (And the other parameters according to your needs, e.g., `num_samples` to `400`, `num_threads` to `1`, `min_handle_inliers` to `3`.)

**Comment by ZQ32** [comment]
thank you very much !!! I wish you all the best.
