### ISSUE TITLE
need more explanations regarding workspace and camera pose in launch file.

### ISSUE THREAD

**Issue by inkyusa** [atenpas/agile_grasp#3]
Hi, thank you for your work.
I am just wondering the the definition of workspace in launch file (e.g., single_camera_grasps.launch). It takes 6 numbers without explanations. It seems the dimensions but is difficult to guess.

From 6.2 Method B, http://wiki.ros.org/agile_grasp, 
and a workspace.txt that lists the workspace dimensions for each file. 
I can't understand workspace.txt file, do you have any example files for this?

My last question is that there is camera pose in the launch file. Is it wrt torso, or another frame?
Thank you.

**Comment by atenpas** [comment]
1. The workspace parameter in the launch file are the dimensions of a box whose center is at the origin. This is used to reduce the point cloud size.
2. Workspace.txt looks like:
   filename1 -1, 1, -1, 1, -1, 1
   filename2 -5, 5, -3, 4, -2, 2
   ...
3. The camera pose parameter should have been removed from those files. It's not used. As long as you use input from a single camera, it is not required.
