### ISSUE TITLE
Use it in UR5 robot ？

### ISSUE THREAD

**Issue by james2254** [atenpas/agile_grasp#4]
I have a ur5 robot,can I use agile_grasp in it.Then when training svm,what's the means of files[i]+l_reg.pcd and files[i]+r_reg.pcd? For a cube,how much pcd should I use for svm-training?
Thank you very much!

**Comment by atenpas** [comment]
You do not need to train the svm.

**Comment by james2254** [comment]
For a new object，it‘s not necessary for training？it‘s useful for any object？

**Comment by atenpas** [comment]
Yes. As long as the object is rigid (some deformable objects will also work) and can be seen by the sensor.

**Comment by james2254** [comment]
Thank you very much！
